/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: {
        // DESIGN.md > Responsive Behavior: mobile 320-599px (default, no
        // min-width needed), tablet 600-1023px, desktop 1024px+.
        tablet: '600px',
        desktop: '1024px',
      },
      colors: {
        primary: '#14110f',
        'on-primary': '#f7f2ea',
        canvas: '#f7f2ea',
        parchment: '#efe6d6',
        ink: '#14110f',
        slate: '#3a352f',
        ash: '#57514a',
        mute: '#83796d',
        hairline: '#d8cdb8',
        'hairline-soft': '#e8e0d0',
        danger: '#a3231f',
        'danger-deep': '#5c1310',
        success: '#2f6b4f',
        'success-bright': '#3f9c73',
        info: '#2d5580',
        'accent-gold': '#b08a2e',
        'accent-gold-soft': '#e6d3a3',
        'accent-blood': '#7a1d1a',
      },
      borderRadius: {
        none: '0px',
        sm: '6px',
        md: '10px',
        lg: '16px',
        full: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '48px',
      },
      fontFamily: {
        'serif-display': ['Fraunces', 'serif'],
        'sans-ui': ['Inter', 'sans-serif'],
        'sans-body': ['Inter', 'sans-serif'],
        'mono-ui': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-title': ['40px', { lineHeight: '1.05', fontWeight: '600' }],
        'heading-xl': ['26px', { lineHeight: '1.2', fontWeight: '600' }],
        'heading-lg': ['20px', { lineHeight: '1.25', fontWeight: '600' }],
        'heading-md': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
        'button-md': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'button-sm': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'link-md': ['16px', { lineHeight: '1.5', fontWeight: '600', textDecoration: 'underline' }],
        'caption-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'caption-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-dice': ['14px', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.02em' }],
        'utility-xs': ['11px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 1px 3px rgba(20,17,15,0.08)',
      },
    },
  },
  plugins: [],
};
