name: jdr

services:
  jdr:
    image: ${IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    env_file: .env
    ports:
      - '127.0.0.1:3005:3000'
    volumes:
      - jdr-data:/app/backend/data

volumes:
  jdr-data:
